FROM node:22-alpine as builder
WORKDIR /usr/src/app
COPY package*.json ./
# install pnpm
RUN npm install -g pnpm
RUN pnpm install
COPY . .
RUN pnpm run build
EXPOSE 3000

FROM node:22-alpine as production
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder  /usr/src/app/package*.json ./
RUN npm install --production
EXPOSE 3000
CMD ["node", "dist/main.js"]